CREATE TABLE Kategori (
	ID SERIAL,
	Navn VARCHAR(45) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE Spraak (
	ID SERIAL,
	Navn VARCHAR(45) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE Utgiver (
	ID SERIAL,
	Navn VARCHAR(128) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE Podkast (
	ID SERIAL,
	KategoriID INT,
	SpraakID INT,
	UtgiverID INT,
	Navn VARCHAR(128) NOT NULL,
	Beskrivelse TEXT NOT NULL,
	Bilde TEXT,
	PRIMARY KEY (ID),
	FOREIGN KEY (KategoriID) REFERENCES Kategori(ID),
	FOREIGN KEY (SpraakID) REFERENCES Spraak(ID),
	FOREIGN KEY (UtgiverID) REFERENCES Utgiver(ID)
);